// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uxorkfsfbhkzykbtuvws.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV4b3JrZnNmYmhrenlrYnR1dndzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA0NDY0NzIsImV4cCI6MjA1NjAyMjQ3Mn0.sM6RK0CasCMq5Kach3RTBPeBSywMg50P9Derpq7PZ74";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);